---
- name: Download vector
  ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
        mode: '0644'
 
- name: Install vector
  become: true
  ansible.builtin.yum:
      name: "/tmp/vector-{{ vector_version }}-1.x86_64.rpm"
      disable_gpg_check: true
  changed_when: false
 
- name: Deploy vector configuration
  become: true
  become_user: root
  ansible.builtin.template:
        src: vector.yml.j2
        dest: "{{ vector_config_dir }}/vector.yml"
        mode: "0644"
        owner: "root"
        group: "root"
        validate: vector validate --no-environment %s
  notify: 
      - Restart vector
      
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
